title: Simran Arora # your name (or website title) here
logo: "/images/IMG_2458.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/simran-arora-88814015a/">LinkedIn</a> | <a href="https://drive.google.com/file/d/1lxbVIpwdyviCLjeAzYQ6_0M5VQP_A9My/view">CV</a> | <a href="https://drive.google.com/file/d/1lxbVIpwdyviCLjeAzYQ6_0M5VQP_A9My/view">Writing Samples</a>
  <br>
  Hi, I'm Sim! Use this website to explore my projects.

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
