title: Simran Arora # your name (or website title) here
logo: "/images/IMG_2458.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Sim! Use this website to explore my projects.
  <a href="https://www.linkedin.com/in/simran-arora-88814015a/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
